// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0_4YGP_UNs5faumlsSZAQUYVRQ0CrBnQ',
    appId: '1:997376757274:android:1a3294b9dc596626704ba3',
    messagingSenderId: '997376757274',
    projectId: 'doctoguidedoctorapp',
    storageBucket: 'doctoguidedoctorapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiZEIROkhhJaUMKD0bFJGTPNjpc4hynqY',
    appId: '1:997376757274:ios:f0167776d2431840704ba3',
    messagingSenderId: '997376757274',
    projectId: 'doctoguidedoctorapp',
    storageBucket: 'doctoguidedoctorapp.appspot.com',
    iosBundleId: 'com.example.doctoGuideDoctorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiZEIROkhhJaUMKD0bFJGTPNjpc4hynqY',
    appId: '1:997376757274:ios:f0167776d2431840704ba3',
    messagingSenderId: '997376757274',
    projectId: 'doctoguidedoctorapp',
    storageBucket: 'doctoguidedoctorapp.appspot.com',
    iosBundleId: 'com.example.doctoGuideDoctorApp',
  );
}
